---
- hosts: ipa
  strategy: free
  gather_facts: False
  tasks:
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding localhost IPV4 address to host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding localhost IPV6 address to host file
    lineinfile:
      path: /etc/hosts
      line: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      create: yes
  - name: Adding ipa to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.10 ipa.eight.example.com ipa.eight
      create: yes
  - name: Adding system address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.11 system1.eight.example.com system1.eight
      create: yes
  - name: Installing Environment Packages
    command: yum install -y httpd vsftpd
#    async: 600
#    poll: 0
#    register: yum_sleeper
#  - name: ---> Not Failing, Just Finishing Environment Package Installation...
#    async_status: jid={{ yum_sleeper.ansible_job_id }}
#    register: job_result
#    until: job_result.finished
#    retries: 50
  - name: Enabling services
    service: name={{item}} enabled=true
    with_items:
      - httpd
      - vsftpd
      - firewalld
      - ntpd
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloading Firewall
    command: firewall-cmd --reload
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.5/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search example.com ipv4.method manual
  - name: Reloading Network Configuration
    shell: nmcli con up "System eth1"  